### ISSUE TITLE
Transfer mongoid-paranoid to github/mongoid

### ISSUE THREAD

**Issue by Fudoshiki** [mongoid/mongoid-paranoid#1]
@dblock Hello, what do you thing about transfer `mongoid-paranoid` to mongoid team

`mongoid-paranoid` replacing `mongoid_paranoia`, which doesn't support mongoid 7
Also I can open PR for `mongoid-slug` for support mongoid 7 and `mongoid-paranoid`

**Comment by dblock** [comment]
Sounds good! Lets do it. If you make me admin here for a minute I can do the transfer.

**Comment by dblock** [comment]
Looks like collaborator isn't enough permissions. Transfer the repo to me and I'll immediately transfer it into mongoid? Promise I won't keep it ;)

**Comment by Fudoshiki** [comment]
accept transfer

**Comment by Fudoshiki** [comment]
@dblock accept ownership

**Comment by dblock** [comment]
Transferred and made @Fudoshiki admin. Enjoy!
